title: Root Network Security
baseurl: ''
email: w3ndige@protonmail.com
author: W3ndige
description: "Beginners's journey through the world of security, programming and system administration. In love with GNU/Linux and cryptography."

# Google tracker
google_analytics: UA-92681943-1

markdown: kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: pretty
paginate: 5
paginate_path: /page:num/

exclude:
- README.md

plugins: [jekyll-paginate, jekyll-seo-tag]
