# Site settings
title: Root Network Security
header-img: img/home-header.jpg
email: w3ndige@protonmail.com
copyright_name: RootNetSec
description: "RootNetSec is a site about journey through the world of network security, pentesting, Linux administration, programming an networking. View to learn more!"
baseurl: ""
url: "https://www.rootnetsec.com"
github_username:  w3ndige
email_username:  w3ndige@protonmail.com
# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-92681943-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
include: ["_pages"]
gems: [jekyll-paginate, jekyll-feed, rouge, jekyll-sitemap]
