#
###################################
# Site wide configuration
####################################
#
title: Root Network Security
email: w3ndige@protonmail.com
description: Beginners's journey through the world of security, programming and system administration. In love with GNU/Linux and cryptography. 
url: https://www.rootnetsec.com
baseurl: ""
keywords: ["blog", "jekyll"]

plugins: [jekyll-paginate]
paginate_path: "/page:num/"
paginate: 5

google_analytics: UA-92681943-1

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Warsaw
markdown:          kramdown
highlighter:       rouge


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: W3ndige
  avatar: w3ndige.jpg
  job: "Student"
  bio: "Beginners's journey through the world of security, programming and system administration. In love with GNU/Linux and cryptography."
  email: w3ndige@protonmail.com
  disqus-shortname:
  twitter: W3ndige
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: W3ndige
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: W3ndige
  telegram: #username
